version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: userdb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: usersdb
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/user:/docker-entrypoint-initdb.d

